### PR TITLE
Added no-referrer meta tag and subresource integrity 

### PR DESCRIPTION
**Pull request by SvenTo**
Hi,
I've added the no-referrer meta tag and subresource integrity for all third-party (CDN) resource to protect  the confidentiality of NMap scans.

### CODE REVIEW

**Comment by honze-net** [comment]
Hi Sven,

Thank you for your contribution. At this point I do not entirely understand the problem. So I try to rephrase it, please correct me, if I am wrong.

At first I see the no-referrer meta tag. This is a good addition and it is out of question, I would like to merge that. But why the other changes. As I understand I added the hashes to pin the external code. In your commit the datatables css is missing. The hashes for the external resources have changed. Can you explain your intention a bit more, so I can understand every change. This would be a great help.

Thanks,

Andreas

**Comment by honze-net** [comment]
Now it looks better, I will test the pull request in my scenarios I created. Unfortunately my build environment has to be reconfigured, because one of my file servers died. So this will take me some time, but I am confident, that the pull request will be merged around next week.

**Comment by SvenTo** [comment]
Hi Andreas,
sorry, I've added the patch but missed to answer the pull request: Yes, the changed it was just a mistake. Thank you for this nice report template! :-)

**Comment by honze-net** [comment]
I merged your pull request into the Dev branch to test it and verify all changes. After that I will merge it into master. Thank you again for your contribution!

**Pull request merged**
