### PR TITLE
Allow collapsing details of online hosts

### PR DESCRIPTION
**Pull request by Anthirian**
I've expanded the template a bit by adding support for collapsing the details of online hosts upon clicking the header bar.

### CODE REVIEW

**Comment by honze-net** [comment]
Hi @Anthirian,
this is a great idea. I tried it and works! But the user has no visual indication, that this is collapsible. Do you have an idea on how to improve that?
Thanks
Andreas

**Comment by Anthirian** [comment]
Thanks. I don’t unfortunately, but I’ll look into it soon.

**Comment by honze-net** [comment]
No problem. I'll have a look, too.

**Comment by Anthirian** [comment]
I think I figured it out, please have a look at the latest version.

**Comment by honze-net** [comment]
This looks great. I have a few notes:
One would be the whitespace between the chevron and the IP address. The space is quite small, I would increase it by a bit, like an n or m wide space.
The second is, that the chevron states are flipped around. They should point right if closed and down if opened. If you click too fast, you can create a race condition, where the chevron will change, but the container will not collapse or the other way round. So it can become inconsistent.

I will have a look and try to come up with a solution for that.

**Comment by Anthirian** [comment]
Yeah I noticed that as well, but I wasn't sure what was causing it.

**Comment by honze-net** [comment]
I found a way to replace the js toggle of glyphicons with css, that reads the state of the container. So no race condition anymore. The glyphicons switched places and I added some padding. I have merged it into a test branch and I will apply all changes there.

**Comment by honze-net** [comment]
Please test my latest commit in the test branch. If it’s okay for you, I will merge this into master after your approval.

**Comment by Anthirian** [comment]
Looks good to me, nice fix :+1:

**Comment by honze-net** [comment]
Thank you very much!

**Pull request merged**
